AWSTemplateFormatVersion: 2010-09-09


Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: "Retain"
    UpdateReplacePolicy: "Retain"
    Properties: 
      BucketName: !Sub "infra-bucket-${AWS::AccountId}"
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      OwnershipControls:
        Rules:
        - ObjectOwnership: BucketOwnerEnforced
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      MetricsConfigurations:
        - Id: !Sub "infra-bucket-${AWS::AccountId}"

  SSLOnlyPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AllowSSLRequestsOnly
          Effect: Deny
          Principal: "*"
          Action: s3:*
          Resource: !Sub 'arn:aws:s3:::${Bucket}/*'
          Condition:
            Bool:
              aws:SecureTransport: 'false'