AWSTemplateFormatVersion: 2010-09-09

Resources:
  # Database cluster username/password stored in AWS Secret Manager

  secretExemploViewer: #usuario de leitura 
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: rds/user/rds_exemplo_viewer
      Description: Reader party user for Aurora
      SecretString: '{"host":"rds-read-only.endpoint.proxy-xxxxxxxxxx.sa-east-1.rds.amazonaws.com","port":"0000","username":"rds_exemplo_viewer","password":"zzzzzzzz","database":"exemploDB"}'
      Tags:
        - Key: Name
          Value: rds/user/rds_exemplo_viewer

  secretExemploWriter: #usuario de escrita
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: rds/user/rds_exemplo_writer
      Description: Writer party user for Aurora
      SecretString: '{"host":"aurora-proxy.proxy-yyyyyyyyy.sa-east-1.rds.amazonaws.com","port":"9999","username":"rds_exemplo_writer","password":"wwwwwww","database":"exemploDB"}'
      Tags:
        - Key: Name
          Value: rds/user/rds_exemplo_writer
