AWSTemplateFormatVersion: 2010-09-09

Resources:
  # table_model_dynamo
  DynamoTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: "table_model_dynamo"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: exemplo_id
          AttributeType: S
        - AttributeName: exemplo2_id
          AttributeType: S
        - AttributeName: exemplo3_dt
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
      GlobalSecondaryIndexes: #lembrando que para alterar o gsi deve excluir primeiro, não tem como alterar e subir
        - IndexName: "table_model_dynamo.exemplo_id"
          KeySchema:
            - AttributeName: "exemplo_id"
              KeyType: "HASH"
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: "table_model_dynamo.exemplo2_id"
          KeySchema:
            - AttributeName: "exemplo2_id"
              KeyType: "HASH"
            - AttributeName: "exemplo3_dt"
              KeyType: "RANGE"
          Projection:
            ProjectionType: KEYS_ONLY